### ISSUE TITLE
Missing requirements.json for widgets

### ISSUE THREAD

**Issue by abrahammartin** [jw35/acp_lobby_screen#1]
Add requirements.json to all widgets so they can be integrated in the smartcambridge.org dashboard framework. More info here: https://github.com/ijl20/tfc_web/blob/dashboard/tfc_web/static/dashboard/widgets/README.md

**Comment by jw35** [comment]
@abrahammartin  Before we go any further, would it be better to make the key in the 'scripts' objects 'src' rather than URL? This has the advantages a) that it matches usage in the <script> tag, and b) that it makes more sense if the source is a file.

```json
{
    "scripts": [
        { 
            "src": "https://unpkg.com/leaflet@1.0.1/dist/leaflet.js",
            "integrity": ",whatever - I don't seem to have one for this..."
        }
    ]
}
```

**Comment by jw35** [comment]
On the same lines, I've realised that CSS files can have integrity checks too so I think we should support them by allowing the "stylesheets" section to contain objects as well as plain strings, though in this case (for consistency with the <link> tag the keys should probably be "href" and "integrity".

```javascript
{
    "stylesheets": [
        { "href": "https://unpkg.com/leaflet@1.3.1/dist/leaflet.js",
          "integrity": "sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw=="
        }
    ]
}
```

**Comment by jw35** [comment]
I've just added a set of requirements.json files (commit b992418), though they assume the two suggested changes above. 

In the process I've realised two drawbacks to this process, though I expect we can live with them:

1) It's a bit hard to be sure you've specified the right requirements because your widget might work but only because some other widget is including something you need. Which will be fine until you remove that other widget. I suppose we can test any one widget by displaying it on a panel by itself.

2) There's nothing to stop two widgets requesting two different versions of the same library, which will probably not end well. Likewise to upgrade our use of any library will require consistently updating each requirements.json file that happens to mention that library.

**Comment by abrahammartin** [comment]
Agree to all the above including the two drawbacks specified in the last comment. I guess we are starting to grasp why most people use iframes (as they the requirements are contained in the iframe only. Closing this issue because the task is done in https://github.com/jw35/acp_lobby_screen/commit/b9924186b48a75c6da3442d50e53ed8395c50591 but @jw35 you should probably open new issues for this two things you mention as they are worth thinking about separately.
